# -*- coding: utf-8 -*-
"""no_dominated.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EFLNaYJof7G6Mzz4IfU3wk9r9XaSp8eL
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""Data da entrega : 16/09

Complete o código (marcado com None) e quando requisitado, escreva textos diretamente nos notebooks. Onde tiver None, substitua pelo seu código. Execute todo notebook e salve tudo em um PDF nomeado como "NomeSobrenome-P1.pdf".
"""

# mount your drive

def no_dominated(pontos):
  """"
  Determina os pontos não dominados de Pareto

  Input:
  pontos = conjunto de pontos [f1 f2]

  Output:
  nd_pontos = pontos não dominados [f1* f2*]

  """

  N = None # quantidade  de pontos


  while N!=0:
    # Há pontos para classificar.
    None # encontre os pontos não dominados





  return nd_pontos # retorne os pontos não dominados

pontos = None # leia as instâncias de teste

# execute sua função no_dominated

# plot os pontos da instancia e os pontos não dominados