# -*- coding: utf-8 -*-
"""wagner_no_dominated.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ML8SHbAhwGZHaKL7HbRMfSzvzckCvlQ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""Data da entrega : 27/02

Complete o código (marcado com None) e quando requisitado, escreva textos diretamente nos notebooks. 
Onde tiver None, substitua pelo seu código. 
Execute todo notebook e salve tudo em um PDF nomeado como "NomeSobrenome-P1.pdf".
"""

# mount your drive

#from google.colab import drive
#drive.mount('/content/drive')

def no_dominated(pontos):
  """
  Determina os pontos não dominados de Pareto

  Input:
  pontos = conjunto de pontos [f1 f2]

  Output:
  nd_pontos = pontos não dominados [f1* f2*]

  """

  N = pontos.shape[0] # quantidade  de pontos
  nd_pontos = [] # Initialize list for non-dominated points

  # The 'while N!=0' condition as written implies N is fixed and would lead to an infinite loop.
  # This loop is effectively acting as a guard, ensuring calculation only if points exist.
  # A 'break' statement is added to ensure it runs once.
  while N != 0:
    # Há pontos para classificar.
    for i in range(N):
      is_dominated = False
      for j in range(N):
        if i == j:
          continue # Don't compare a point with itself

        # Check if pontos[j] dominates pontos[i]
        # Assuming minimization for both objectives (smaller values are better)
        # A point A dominates point B if A is better or equal in all objectives
        # AND strictly better in at least one objective.
        if (pontos[j, 0] <= pontos[i, 0] and pontos[j, 1] <= pontos[i, 1]) and \
           (pontos[j, 0] < pontos[i, 0] or pontos[j, 1] < pontos[i, 1]):
          is_dominated = True
          break # pontos[i] is dominated, no need to check further

      if not is_dominated:
        nd_pontos.append(pontos[i])

    break # Prevent infinite loop, as N is a fixed initial count.

  return np.array(nd_pontos) # retorne os pontos não dominados as a NumPy array

"""
pontos = np.array([
    [10, 2],
    [8, 4],
    [6, 6],
    [4, 8],
    [2, 10],
    [9, 1],
    [7, 3],
    [5, 5],
    [3, 7],
    [1, 9]
]) # Test instances
"""
pontos = np.array([[8 ,5],
[9, 2],
[12, 1],
[11, 2],
[16, 2]
])

nd_pontos_result = no_dominated(pontos)
print("Pontos Não Dominados:\n", nd_pontos_result)

# plot os pontos da instancia e os pontos não dominados

import matplotlib.lines as mlines

# Create custom legend handles
blue_dot = mlines.Line2D([], [], color='blue', marker='o', linestyle='None',
                         markersize=6, label='Pontos da Instância')
red_dot = mlines.Line2D([], [], color='red', marker='o', linestyle='None',
                        markersize=10, markeredgecolor='black', label='Pontos Não Dominados')

plt.figure(figsize=(8, 6))
plt.scatter(pontos[:, 0], pontos[:, 1], color='blue', alpha=0.7) # Removed 'label' argument
plt.scatter(nd_pontos_result[:, 0], nd_pontos_result[:, 1], color='red', s=100, edgecolors='black', zorder=5) # Removed 'label' argument

plt.title('Pontos da Instância e Pontos Não Dominados')
plt.xlabel('Objetivo 1')
plt.ylabel('Objetivo 2')
plt.grid(True)
plt.legend(handles=[blue_dot, red_dot]) # Use the custom handles for the legend
plt.show()