# -*- coding: utf-8 -*-
"""WagnerTironiPinto_no_dominated.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U2YNTCTqHbLjXg5s3tdZC1TszWanADKY
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.lines as mlines
import os

#from google.colab import drive
#drive.mount('/content/drive')

# Criar uma pasta para as imagens no Drive, se não existir
output_dir = '/content/drive/MyDrive/imagens_P1'
os.makedirs(output_dir, exist_ok=True)
print(f"Diretório de saída para imagens: {output_dir}")

def gera_imagem(fig, filename_prefix):
    output_dir = '/content/drive/MyDrive/imagens_P1'
    # Salva a figura
    filepath = os.path.join(output_dir, f'{filename_prefix}.png')
    fig.savefig(filepath)
    plt.close(fig) # Fechar a figura para liberar memória
    print(f"Imagem salva em: {filepath}")

"""Data da entrega : 16/09

Complete o código (marcado com None) e quando requisitado, escreva textos diretamente nos notebooks. Onde tiver None, substitua pelo seu código. Execute todo notebook e salve tudo em um PDF nomeado como "NomeSobrenome-P1.pdf".
"""

def no_dominated(pontos):
    """"
    Determina os pontos não dominados de Pareto

    Input:
    pontos = conjunto de pontos [f1 f2]

    Output:
    nd_pontos = pontos não dominados [f1* f2*]

    """

    N = pontos.shape[0] # quantidade  de pontos
    nd_pontos = []

    while N!=0:
        # Há pontos para classificar.
        #None # encontre os pontos não dominados
        for i in range(N):
            dominante = False
            for j in range(N):
                if i != j:
                    if pontos[j][0] <= pontos[i][0] and pontos[j][1] <= pontos[i][1]:
                        dominante = True
                        break
            if not dominante:
                nd_pontos.append(pontos[i])

        break

    return nd_pontos # retorne os pontos não dominados

def gera_grafico(pontos, nd_pontos, filename_prefix):
    blue_dot = mlines.Line2D([], [], color='blue', marker='o', linestyle='None',
                            markersize=6, label='Pontos da Instância')
    red_dot = mlines.Line2D([], [], color='red', marker='o', linestyle='None',
                            markersize=10, markeredgecolor='black', label='Pontos Não Dominados')

    fig = plt.figure(figsize=(8, 6))
    plt.scatter(pontos[:, 0], pontos[:, 1], color='blue', alpha=0.7)

    # Convert nd_pontos to a numpy array to enable slicing
    nd_pontos = np.array(nd_pontos)
    plt.scatter(nd_pontos[:, 0], nd_pontos[:, 1], color='red', s=100, edgecolors='black', zorder=5)

    plt.title('Pontos da Instância e Pontos Não Dominados')
    plt.xlabel('f1')
    plt.ylabel('f2')
    plt.grid(True)
    plt.legend(handles=[blue_dot, red_dot])

    gera_imagem(fig, filename_prefix) # Save the figure

pontos = np.array([[8 ,5], [9, 2], [12, 1], [11, 2], [16, 2] ])#None # leia as instâncias de teste

# execute sua função no_dominated
nd_pontos = no_dominated(pontos)
print("Pontos Não Dominados:\n", nd_pontos)

gera_grafico(pontos, nd_pontos, 'exemplo_inicial')

"""### Outros Arrays de Teste para Validação"""

# Teste Array 1: Menor número de pontos, com alguns pontos dominados e outros não
# Gerar pontos em uma área menor para criar mais sobreposição
pontos = np.array([
    [1, 5],
    [2, 4],
    [3, 3],
    [4, 2],
    [5, 1],
    [2, 5], # Dominado por [1,5] e [2,4] (no sentido de minimização, se for maximização não)
    [4, 3]  # Dominado por [3,3] e [4,2]
])

# execute sua função no_dominated
nd_pontos = no_dominated(pontos)
print("Pontos Não Dominados:\n", nd_pontos)

gera_grafico(pontos, nd_pontos, 'teste_array_1')

# Teste Array 2: Maior número de pontos aleatórios em um range diferente
np.random.seed(13) # Outra seed para reprodutibilidade
pontos = np.random.randint(50, 150, size=(30, 2))

print("\nPontos de Teste 2 (primeiras 5 linhas):\n", pontos[:5])

# execute sua função no_dominated
nd_pontos = no_dominated(pontos)
print("Pontos Não Dominados:\n", nd_pontos)

gera_grafico(pontos, nd_pontos, 'teste_array_2')

"""Teste da apostila"""

# Teste Array 3: Pontos que formam uma linha reta (todos devem ser não dominados ou quase todos)
# para um problema de minimização
pontos = np.array([
    [10, 1],
    [8, 2],
    [6, 3],
    [4, 4],
    [2, 5]
])

print("\nPontos de Teste 3:\n", pontos)

# execute sua função no_dominated
nd_pontos = no_dominated(pontos)
print("Pontos Não Dominados:\n", nd_pontos)

gera_grafico(pontos, nd_pontos, 'teste_array_3')

"""### Aplicando `no_dominated` aos dados fornecidos pelo usuário"""

# Dados fornecidos pelo usuário (PONTO 1, PONTO 2)
pontos_csv = np.array([
    [403, 94],
    [886, 506],
    [814, 416],
    [1151, 992],
    [983, 649],
    [629, 237],
    [848, 457],
    [1074, 815],
    [839, 446],
    [819, 422],
    [1062, 791],
    [762, 359],
    [994, 667],
    [950, 598],
    [111, 7],
    [914, 544],
    [737, 334],
    [1049, 766],
    [1152, 994],
    [1110, 893]
])

print("Dados de entrada (PONTO 1, PONTO 2):")
display(pontos_csv)

# Execute a função no_dominated com os pontos do CSV
nd_pontos_csv = no_dominated(pontos_csv)

print("\nPontos Não Dominados a partir dos dados fornecidos:")
# Converte a lista de arrays NumPy para um único array NumPy para exibição limpa
display(np.array(nd_pontos_csv))

gera_grafico(pontos_csv, nd_pontos_csv, 'dados_usuario')

"""### Novo Teste com Dados Estendidos"""

# Dados fornecidos pelo usuário para o novo teste
pontos_novo_teste = np.array([
    [403, 94],
    [886, 506],
    [814, 416],
    [1151, 992],
    [983, 649],
    [629, 237],
    [848, 457],
    [1074, 815],
    [839, 446],
    [819, 422],
    [1062, 791],
    [762, 359],
    [994, 667],
    [950, 598],
    [111, 7],
    [914, 544],
    [737, 334],
    [1049, 766],
    [1152, 994],
    [1110, 893],
    [973, 633],
    [474, 131],
    [824, 428],
    [1013, 700],
    [963, 617],
    [1101, 874],
    [1024, 720],
    [816, 419],
    [1063, 794],
    [575, 196],
    [1153, 997],
    [447, 116],
    [1117, 908],
    [910, 539],
    [1017, 707],
    [931, 569],
    [909, 537],
    [1126, 931],
    [1027, 726],
    [871, 487],
    [1052, 772],
    [891, 513],
    [375, 81],
    [1131, 943],
    [318, 58],
    [705, 303],
    [1048, 764],
    [908, 536],
    [1026, 724],
    [1061, 789]
])

print("Dados de entrada para o Novo Teste (PONTO 1, PONTO 2):")
display(pontos_novo_teste)

# Execute a função no_dominated com os pontos do novo teste
nd_pontos_novo_teste = no_dominated(pontos_novo_teste)

print("\nPontos Não Dominados a partir dos dados do Novo Teste:")
# Converte a lista de arrays NumPy para um único array NumPy para exibição limpa
display(np.array(nd_pontos_novo_teste))

gera_grafico(pontos_novo_teste, nd_pontos_novo_teste, 'novo_teste')

"""### Segundo Novo Teste com Dados Ainda Mais Estendidos"""

# Dados fornecidos pelo usuário para o segundo novo teste
pontos_segundo_teste = np.array([
    [403, 94],
    [886, 506],
    [814, 416],
    [1151, 992],
    [983, 649],
    [629, 237],
    [848, 457],
    [1074, 815],
    [839, 446],
    [819, 422],
    [1062, 791],
    [762, 359],
    [994, 667],
    [950, 598],
    [111, 7],
    [914, 544],
    [737, 334],
    [1049, 766],
    [1152, 994],
    [1110, 893],
    [973, 633],
    [474, 131],
    [824, 428],
    [1013, 700],
    [963, 617],
    [1101, 874],
    [1024, 720],
    [816, 419],
    [1063, 794],
    [575, 196],
    [1153, 997],
    [447, 116],
    [1117, 908],
    [910, 539],
    [1017, 707],
    [931, 569],
    [909, 537],
    [1126, 931],
    [1027, 726],
    [871, 487],
    [1052, 772],
    [891, 513],
    [375, 81],
    [1131, 943],
    [318, 58],
    [705, 303],
    [1048, 764],
    [908, 536],
    [1026, 724],
    [1061, 789],
    [865, 479],
    [493, 142],
    [742, 339],
    [978, 641],
    [575, 196],
    [877, 494],
    [339, 66],
    [1078, 824],
    [592, 208],
    [1019, 711],
    [1066, 800],
    [717, 314],
    [690, 289],
    [800, 401],
    [855, 466],
    [1006, 689],
    [1082, 833],
    [614, 225],
    [638, 244],
    [1090, 849],
    [441, 113],
    [780, 379],
    [764, 361],
    [337, 65],
    [871, 486],
    [1005, 686],
    [687, 286],
    [1108, 889],
    [205, 24],
    [875, 491],
    [1109, 891],
    [395, 90],
    [554, 181],
    [600, 214],
    [173, 17],
    [860, 472],
    [815, 418],
    [816, 419],
    [759, 356],
    [1002, 682],
    [708, 306],
    [582, 201],
    [786, 385],
    [1135, 952],
    [881, 500],
    [572, 194],
    [1033, 737],
    [727, 324],
    [1151, 992],
    [613, 224]
])

print("Dados de entrada para o Segundo Novo Teste (PONTO 1, PONTO 2):")
display(pontos_segundo_teste)

# Execute a função no_dominated com os pontos do segundo novo teste
nd_pontos_segundo_teste = no_dominated(pontos_segundo_teste)

print("\nPontos Não Dominados a partir dos dados do Segundo Novo Teste:")
# Converte a lista de arrays NumPy para um único array NumPy para exibição limpa
display(np.array(nd_pontos_segundo_teste))

gera_grafico(pontos_segundo_teste, nd_pontos_segundo_teste, 'segundo_novo_teste')

"""### Terceiro Novo Teste com Dados Mais Estendidos"""

# Dados fornecidos pelo usuário para o terceiro novo teste
pontos_terceiro_teste = np.array([
    [403, 94],
    [886, 506],
    [814, 416],
    [1151, 992],
    [983, 649],
    [629, 237],
    [848, 457],
    [1074, 815],
    [839, 446],
    [819, 422],
    [1062, 791],
    [762, 359],
    [994, 667],
    [950, 598],
    [111, 7],
    [914, 544],
    [737, 334],
    [1049, 766],
    [1152, 994],
    [1110, 893],
    [973, 633],
    [474, 131],
    [824, 428],
    [1013, 700],
    [963, 617],
    [1101, 874],
    [1024, 720],
    [816, 419],
    [1063, 794],
    [575, 196],
    [1153, 997],
    [447, 116],
    [1117, 908],
    [910, 539],
    [1017, 707],
    [931, 569],
    [909, 537],
    [1126, 931],
    [1027, 726],
    [871, 487],
    [1052, 772],
    [891, 513],
    [375, 81],
    [1131, 943],
    [318, 58],
    [705, 303],
    [1048, 764],
    [908, 536],
    [1026, 724],
    [1061, 789],
    [865, 479],
    [493, 142],
    [742, 339],
    [978, 641],
    [575, 196],
    [877, 494],
    [339, 66],
    [1078, 824],
    [592, 208],
    [1019, 711],
    [1066, 800],
    [717, 314],
    [690, 289],
    [800, 401],
    [855, 466],
    [1006, 689],
    [1082, 833],
    [614, 225],
    [638, 244],
    [1090, 849],
    [441, 113],
    [780, 379],
    [764, 361],
    [337, 65],
    [871, 486],
    [1005, 686],
    [687, 286],
    [1108, 889],
    [205, 24],
    [875, 491],
    [1109, 891],
    [395, 90],
    [554, 181],
    [600, 214],
    [173, 17],
    [860, 472],
    [815, 418],
    [816, 419],
    [759, 356],
    [1002, 682],
    [708, 306],
    [582, 201],
    [786, 385],
    [1135, 952],
    [881, 500],
    [572, 194],
    [1033, 737],
    [727, 324],
    [1151, 992],
    [613, 224],
    [865, 479],
    [493, 142],
    [742, 339],
    [978, 641],
    [575, 196],
    [877, 494],
    [339, 66],
    [1078, 824],
    [592, 208],
    [1019, 711],
    [1066, 800],
    [717, 314],
    [690, 289],
    [800, 401],
    [855, 466],
    [1006, 689],
    [1082, 833],
    [614, 225],
    [638, 244],
    [1090, 849],
    [441, 113],
    [780, 379],
    [764, 361],
    [337, 65],
    [871, 486],
    [1005, 686],
    [687, 286],
    [1108, 889],
    [205, 24],
    [875, 491],
    [1109, 891],
    [395, 90],
    [554, 181],
    [600, 214],
    [173, 17],
    [860, 472],
    [815, 418],
    [816, 419],
    [759, 356],
    [1002, 682],
    [708, 306],
    [582, 201],
    [786, 385],
    [1135, 952],
    [881, 500],
    [572, 194],
    [1033, 737],
    [727, 324],
    [1151, 992],
    [613, 224]
])

print("Dados de entrada para o Terceiro Novo Teste (PONTO 1, PONTO 2):")
display(pontos_terceiro_teste)

# Execute a função no_dominated com os pontos do terceiro novo teste
nd_pontos_terceiro_teste = no_dominated(pontos_terceiro_teste)

print("\nPontos Não Dominados a partir dos dados do Terceiro Novo Teste:")
# Converte a lista de arrays NumPy para um único array NumPy para exibição limpa
display(np.array(nd_pontos_terceiro_teste))

gera_grafico(pontos_terceiro_teste, nd_pontos_terceiro_teste, 'terceiro_novo_teste')

"""### Quarto Novo Teste com Dados Ainda Mais Estendidos"""

# Dados fornecidos pelo usuário para o quarto novo teste
pontos_quarto_teste = np.array([
    [403, 94],
    [886, 506],
    [814, 416],
    [1151, 992],
    [983, 649],
    [629, 237],
    [848, 457],
    [1074, 815],
    [839, 446],
    [819, 422],
    [1062, 791],
    [762, 359],
    [994, 667],
    [950, 598],
    [111, 7],
    [914, 544],
    [737, 334],
    [1049, 766],
    [1152, 994],
    [1110, 893],
    [973, 633],
    [474, 131],
    [824, 428],
    [1013, 700],
    [963, 617],
    [1101, 874],
    [1024, 720],
    [816, 419],
    [1063, 794],
    [575, 196],
    [1153, 997],
    [447, 116],
    [1117, 908],
    [910, 539],
    [1017, 707],
    [931, 569],
    [909, 537],
    [1126, 931],
    [1027, 726],
    [871, 487],
    [1052, 772],
    [891, 513],
    [375, 81],
    [1131, 943],
    [318, 58],
    [705, 303],
    [1048, 764],
    [908, 536],
    [1026, 724],
    [1061, 789],
    [865, 479],
    [493, 142],
    [742, 339],
    [978, 641],
    [575, 196],
    [877, 494],
    [339, 66],
    [1078, 824],
    [592, 208],
    [1019, 711],
    [1066, 800],
    [717, 314],
    [690, 289],
    [800, 401],
    [855, 466],
    [1006, 689],
    [1082, 833],
    [614, 225],
    [638, 244],
    [1090, 849],
    [441, 113],
    [780, 379],
    [764, 361],
    [337, 65],
    [871, 486],
    [1005, 686],
    [687, 286],
    [1108, 889],
    [205, 24],
    [875, 491],
    [1109, 891],
    [395, 90],
    [554, 181],
    [600, 214],
    [173, 17],
    [860, 472],
    [815, 418],
    [816, 419],
    [759, 356],
    [1002, 682],
    [708, 306],
    [582, 201],
    [786, 385],
    [1135, 952],
    [881, 500],
    [572, 194],
    [1033, 737],
    [727, 324],
    [1151, 992],
    [613, 224],
    [865, 479],
    [493, 142],
    [742, 339],
    [978, 641],
    [575, 196],
    [877, 494],
    [339, 66],
    [1078, 824],
    [592, 208],
    [1019, 711],
    [1066, 800],
    [717, 314],
    [690, 289],
    [800, 401],
    [855, 466],
    [1006, 689],
    [1082, 833],
    [614, 225],
    [638, 244],
    [1090, 849],
    [441, 113],
    [780, 379],
    [764, 361],
    [337, 65],
    [871, 486],
    [1005, 686],
    [687, 286],
    [1108, 889],
    [205, 24],
    [875, 491],
    [1109, 891],
    [395, 90],
    [554, 181],
    [600, 214],
    [173, 17],
    [860, 472],
    [815, 418],
    [816, 419],
    [759, 356],
    [1002, 682],
    [708, 306],
    [582, 201],
    [786, 385],
    [1135, 952],
    [881, 500],
    [572, 194],
    [1033, 737],
    [727, 324],
    [1151, 992],
    [613, 224],
    [865, 479],
    [493, 142],
    [742, 339],
    [978, 641],
    [575, 196],
    [877, 494],
    [339, 66],
    [1078, 824],
    [592, 208],
    [1019, 711],
    [1066, 800],
    [717, 314],
    [690, 289],
    [800, 401],
    [855, 466],
    [1006, 689],
    [1082, 833],
    [614, 225],
    [638, 244],
    [1090, 849],
    [441, 113],
    [780, 379],
    [764, 361],
    [337, 65],
    [871, 486],
    [1005, 686],
    [687, 286],
    [1108, 889],
    [205, 24],
    [875, 491],
    [1109, 891],
    [395, 90],
    [554, 181],
    [600, 214],
    [173, 17],
    [860, 472],
    [815, 418],
    [816, 419],
    [759, 356],
    [1002, 682],
    [708, 306],
    [582, 201],
    [786, 385],
    [1135, 952],
    [881, 500],
    [572, 194],
    [1033, 737],
    [727, 324],
    [1151, 992],
    [613, 224]
])

print("Dados de entrada para o Quarto Novo Teste (PONTO 1, PONTO 2):")
display(pontos_quarto_teste)

# Execute a função no_dominated com os pontos do quarto novo teste
nd_pontos_quarto_teste = no_dominated(pontos_quarto_teste)

print("\nPontos Não Dominados a partir dos dados do Quarto Novo Teste:")
# Converte a lista de arrays NumPy para um único array NumPy para exibição limpa
display(np.array(nd_pontos_quarto_teste))

gera_grafico(pontos_quarto_teste, nd_pontos_quarto_teste, 'quarto_novo_teste')

"""### Processando o arquivo CSV completo: `/content/knapPI_16_100_1000.csv`"""

file_path = '/content/knapPI_16_100_1000.csv'

# Vamos inspecionar as primeiras linhas do novo arquivo para entender sua estrutura
print(f"Conteúdo do arquivo {file_path} (primeiras 20 linhas):\n")

with open(file_path, 'r') as f:
    for i, line in enumerate(f):
        print(f"Linha {i+1}: {line.strip()}")
        if i >= 19: # Imprimir as primeiras 20 linhas
            break

print("\nIsso nos ajuda a entender o formato do cabeçalho e dos separadores.")

"""Com base na inspeção do arquivo, cada 'entrada' ou 'bloco' de dados é separada pela linha `-----`. Além disso, cada bloco começa com 5 linhas de metadados (`knapPI...`, `n`, `c`, `z`, `time`). As colunas de interesse para os pontos (f1, f2) estão na segunda e terceira posição (índices 1 e 2) após as linhas de metadados e a primeira coluna de índice.

Agora vou criar uma função para ler o arquivo completo, dividir em entradas, extrair os pontos e aplicar a função `no_dominated` em cada uma.
"""

def process_csv_entries(file_path):
    with open(file_path, 'r') as f:
        lines = f.readlines()

    entries_data = []
    current_entry_lines = []

    for line in lines:
        stripped_line = line.strip()
        if stripped_line == '-----':
            if current_entry_lines:
                entries_data.append(current_entry_lines)
            current_entry_lines = [] # Reset for the next entry
        else:
            current_entry_lines.append(stripped_line)

    # Add the last entry if it's not empty
    if current_entry_lines:
        entries_data.append(current_entry_lines)

    results = {}
    for i, entry_lines in enumerate(entries_data):
        # Skip metadata lines (first 5 lines) and process actual data
        data_lines = entry_lines[5:] # Assuming first 5 lines are metadata

        # Filter out empty lines or non-data lines within the data_lines segment
        parsed_points = []
        for dl in data_lines:
            parts = dl.split(',')
            if len(parts) >= 3 and parts[0].isdigit(): # Ensure it's a data line with at least 3 parts and starts with a digit
                try:
                    f1 = float(parts[1])
                    f2 = float(parts[2])
                    parsed_points.append([f1, f2])
                except ValueError:
                    # Skip lines that can't be converted to float (e.g., malformed lines)
                    continue

        if parsed_points: # Process only if there are valid points
            points_array = np.array(parsed_points)
            nd_points = no_dominated(points_array)
            results[f'Entrada {i+1}'] = np.array(nd_points)
            # Generate plot for each entry's non-dominated points
            if len(nd_points) > 0:
                # Generate a plot for each entry and save it
                fig_entry = plt.figure(figsize=(8, 6))
                plt.scatter(points_array[:, 0], points_array[:, 1], color='blue', alpha=0.7, label='Todos os Pontos')
                plt.scatter(np.array(nd_points)[:, 0], np.array(nd_points)[:, 1], color='red', s=100, edgecolors='black', zorder=5, label='Pontos Não Dominados')
                plt.title(f'Pontos Não Dominados para {entry_lines[0]}') # Use first line of entry as title
                plt.xlabel('f1')
                plt.ylabel('f2')
                plt.grid(True)
                plt.legend()
                gera_imagem(fig_entry, f'entrada_{i+1}')
        else:
            results[f'Entrada {i+1}'] = np.array([]) # No valid points found for this entry

    return results

# Processar o arquivo e obter os pontos não dominados para cada entrada
all_nd_points_summary = process_csv_entries(file_path)

# Apresentar os resultados de forma resumida
print("\n--- Resumo dos Pontos Não Dominados por Entrada ---")
for entry_name, nd_points in all_nd_points_summary.items():
    if nd_points.size > 0:
        print(f"\n{entry_name}:")
        display(nd_points)
    else:
        print(f"\n{entry_name}: Não foram encontrados pontos válidos para esta entrada ou está vazia.")

